<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Config Block ({name})' => 'Настройки блока ({name})',
    'Create Block ({name})' => '@@Создать блок ({name})@@',
    'Are you sure you want to delete this item?' => 'Вы уверенны что хотите удалить этот элемент?',
    'Available Blocks' => 'Доступные блоки',
    'Block Name' => 'Название блока',
    'Block Type' => 'Тип блока',
    'Blocks' => 'Блоки',
    'CMS' => 'CMS',
    'Config' => 'Конфигурации',
    'Create' => 'Создать',
    'Create Block' => 'Создать блок',
    'Create Page' => 'Создать страницу',
    'Created At' => 'Создано',
    'Delete' => 'Удалить',
    'ID' => 'ID',
    'Layout' => 'Макет',
    'Layout file must exist' => 'Макет должен существовать',
    'List' => 'Список',
    'Page Content' => 'Контент страницы',
    'Page not found.' => 'Страница не найдена.',
    'Pages' => 'Страницы',
    'Route' => 'Маршрут',
    'Save' => 'Сохранить',
    'Title' => 'Заголовок',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновить {modelClass}: ',
    'Updated At' => 'Обновлено',
    'e.g. @app/views/layouts/main' => 'т.к. @app/views/layouts/main',
];
