<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new block' => '',
    'Are you sure you want to delete this item?' => '',
    'Available Blocks' => '',
    'Base layout' => '',
    'Block "{id}" not found' => '',
    'Block Name' => '',
    'Block Type' => '',
    'Block type' => '',
    'Blocks' => '',
    'CMS' => '',
    'Config' => '',
    'Config Block ({name})' => '',
    'Content' => '',
    'Content type' => '',
    'Create' => '',
    'Create Block' => '',
    'Create Page' => '',
    'Created At' => '',
    'Delete' => '',
    'ID' => '',
    'Layout' => '',
    'Layout file must exist' => '',
    'List' => '',
    'Meta Tags' => '',
    'Meta description' => '',
    'Meta keywords' => '',
    'Meta robots' => '',
    'Meta title' => '',
    'N/A' => '',
    'Page Content' => '',
    'Page not found.' => '',
    'Pages' => '',
    'Protected visibility' => '',
    'Public visibility' => '',
    'Route' => '',
    'Save' => '',
    'Title' => '',
    'Type' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updating Page' => '',
    'Visibility' => '',
];
