<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Config Block ({name})' => 'Налаштування блоку ({name})',
    'ID' => '',
    'Create Block ({name})' => '@@Створити блок ({name})@@',
    'Are you sure you want to delete this item?' => 'Ви дійсно хочете видалити цей запис?',
    'Available Blocks' => 'Доступні блоки',
    'Block Name' => 'Назва блоку',
    'Block Type' => 'Тип блоку',
    'Blocks' => 'Блоки',
    'CMS' => 'Керування контентом',
    'Config' => 'Налаштування',
    'Create' => 'Створити',
    'Create Block' => 'Створити блок',
    'Create Page' => 'Створити сторінку',
    'Created At' => 'Створено',
    'Delete' => 'Видалити',
    'Layout' => 'Схема',
    'Layout file must exist' => 'Файл схеми повинен бути присутнім',
    'List' => 'Список',
    'Page Content' => 'Вміст сторінки',
    'Page not found.' => 'Сторінку не знайдено',
    'Pages' => 'Сторінки',
    'Route' => 'Маршрут',
    'Save' => 'Зберегти',
    'Title' => 'Заголовок',
    'Update' => 'Редагувати',
    'Update {modelClass}: ' => 'Редагувати {modelClass}:',
    'Updated At' => 'Оновлено',
    'e.g. @app/views/layouts/main' => 'Наприклад @app/views/layouts/main',
];
