<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Files' => 'Файли',
    'ID' => '',
    'Meta description' => '',
    'Meta keywords' => '',
    'Meta robots' => '',
    'Meta title' => '',
    'Add Menu Item' => 'Додати пункт меню',
    'Add new block' => 'Додати новий блок',
    'Are you sure you want to delete this item?' => 'Ви дійсно хочете видалити цей запис?',
    'Available Blocks' => 'Доступні блоки',
    'Base layout' => 'Базовий шаблон',
    'Block "{id}" not found' => 'Блок "{id}" не знайдено',
    'Block Name' => 'Назва блоку',
    'Block Type' => 'Тип блоку',
    'Block type' => 'Блочний тип',
    'Blocks' => 'Блоки',
    'CMS' => 'Керування контентом',
    'Config' => 'Налаштування',
    'Config Block ({name})' => 'Налаштування блоку ({name})',
    'Content' => 'Контент',
    'Content type' => 'Одна сторінка',
    'Create' => 'Створити',
    'Create Block' => 'Створити блок',
    'Create Page' => 'Створити сторінку',
    'Created At' => 'Створено',
    'Delete' => 'Видалити',
    'Layout' => 'Схема',
    'Layout file must exist' => 'Файл схеми повинен бути присутнім',
    'List' => 'Список',
    'Meta Tags' => 'Meta теги',
    'N/A' => 'Не вказано',
    'Name' => 'Назва',
    'Page Content' => 'Вміст сторінки',
    'Page not found.' => 'Сторінку не знайдено',
    'Pages' => 'Сторінки',
    'Protected visibility' => 'Приховано',
    'Public visibility' => 'Публічна видимість',
    'Remove' => 'Видалити',
    'Route' => 'Маршрут',
    'Save' => 'Зберегти',
    'Tag' => 'Тег',
    'Tag class' => 'CSS клас для тега',
    'This block is used on page!' => 'Цей блок використовується на сторінці!',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'Update' => 'Редагувати',
    'Update {modelClass}: ' => 'Редагувати {modelClass}:',
    'Updated At' => 'Оновлено',
    'Updating Page' => 'Редагування сторінки',
    'Url' => 'Посилання',
    'Visibility' => 'Видимість',
    'Save and Continue Edit' => 'Зберегти та продовжити редагування',
];
